services:
  postgres:
    image: postgres:16
    container_name: mini-postgres

    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .

    container_name: mini-api

    volumes:
    - ./internal/config/config.yaml:/app/config/config.yaml
    
    depends_on:
      - postgres

    ports:
      - "18080:18080"

    environment:
      DB_DSN: postgres://app:app@postgres:5432/appdb?sslmode=disable
      CONFIG_PATH: /app/config/config.yaml

volumes:
  postgres_data: